#!/usr/bin/python
# -*- coding: utf-8 -*-
import os, sys

C = {"uníssono": "C",
            "2a menor": "Db",
            "2a Maior": "D",
            "2a Aumentada": "D#",
            "3a menor": "Eb",
            "3a Maior": "E",
            "4a Justa": "F",
            "4a Aumentada": "F#",
            "5a diminuta": "Gb",
            "5a Justa": "G",
            "5a Aumentada": "G#",
            "6a menor": "Ab",
            "6a Maior": "A",
            "7a diminuta": "Bbb",
            "7a menor": "Bb",
            "7a Maior": "B",
            }

C_sus = {"uníssono": "C#",
            "2a menor": "D",
            "2a Maior": "D#",
            "2a Aumentada": "D##",
            "3a menor": "E",
            "3a Maior": "E#",
            "4a Justa": "F#",
            "4a Aumentada": "F##",
            "5a diminuta": "G",
            "5a Justa": "G#",
            "5a Aumentada": "G##",
            "6a menor": "A",
            "6a Maior": "A#",
            "7a diminuta": "Bb",
            "7a menor": "B",
            "7a Maior": "B#",
            }

C_b = {"uníssono": "Cb",
            "2a menor": "Dbb",
            "2a Maior": "Db",
            "2a Aumentada": "D",
            "3a menor": "Ebb",
            "3a Maior": "Eb",
            "4a Justa": "Fb",
            "4a Aumentada": "F",
            "5a diminuta": "Gbb",
            "5a Justa": "Gb",
            "5a Aumentada": "G",
            "6a menor": "Abb",
            "6a Maior": "Ab",
            "7a diminuta": "Bbbb",
            "7a menor": "Bbb",
            "7a Maior": "Bb",
            }

D = {"uníssono": "D",
            "2a menor": "Eb",
            "2a Maior": "E",
            "2a Aumentada": "E#",
            "3a menor": "F",
            "3a Maior": "F#",
            "4a Justa": "G",
            "4a Aumentada": "G#",
            "5a diminuta": "Ab",
            "5a Justa": "A",
            "5a Aumentada": "A#",
            "6a menor": "Bb",
            "6a Maior": "B",
            "7a diminuta": "Cb",
            "7a menor": "C",
            "7a Maior": "C#",
            }

D_sus = {"uníssono": "D#",
            "2a menor": "E",
            "2a Maior": "E#",
            "2a Aumentada": "E##",
            "3a menor": "F#",
            "3a Maior": "F##",
            "4a Justa": "G#",
            "4a Aumentada": "G##",
            "5a diminuta": "A",
            "5a Justa": "A#",
            "5a Aumentada": "A##",
            "6a menor": "B",
            "6a Maior": "B#",
            "7a diminuta": "C",
            "7a menor": "C#",
            "7a Maior": "C##",
            }

D_b = {"uníssono": "Db",
            "2a menor": "Ebb",
            "2a Maior": "Eb",
            "2a Aumentada": "E",
            "3a menor": "Fb",
            "3a Maior": "F",
            "4a Justa": "Gb",
            "4a Aumentada": "G",
            "5a diminuta": "Abb",
            "5a Justa": "Ab",
            "5a Aumentada": "A",
            "6a menor": "Bbb",
            "6a Maior": "Bb",
            "7a diminuta": "Cbb",
            "7a menor": "Cb",
            "7a Maior": "C",
            }

E = {"uníssono": "E",
            "2a menor": "F",
            "2a Maior": "F#",
            "2a Aumentada": "F##",
            "3a menor": "G",
            "3a Maior": "G#",
            "4a Justa": "A",
            "4a Aumentada": "A#",
            "5a diminuta": "Bb",
            "5a Justa": "B",
            "5a Aumentada": "B#",
            "6a menor": "C",
            "6a Maior": "C#",
            "7a diminuta": "Db",
            "7a menor": "D",
            "7a Maior": "D#",
            }

E_sus = {"uníssono": "E#",
            "2a menor": "F#",
            "2a Maior": "F##",
            "2a Aumentada": "F###",
            "3a menor": "G#",
            "3a Maior": "G##",
            "4a Justa": "A#",
            "4a Aumentada": "A##",
            "5a diminuta": "B",
            "5a Justa": "B#",
            "5a Aumentada": "B##",
            "6a menor": "C#",
            "6a Maior": "C##",
            "7a diminuta": "D",
            "7a menor": "D#",
            "7a Maior": "D##",
            }

E_b = {"uníssono": "Eb",
            "2a menor": "Fb",
            "2a Maior": "F",
            "2a Aumentada": "F#",
            "3a menor": "Gb",
            "3a Maior": "G",
            "4a Justa": "Ab",
            "4a Aumentada": "A",
            "5a diminuta": "Bbb",
            "5a Justa": "Bb",
            "5a Aumentada": "B",
            "6a menor": "Cb",
            "6a Maior": "C",
            "7a diminuta": "Dbb",
            "7a menor": "Db",
            "7a Maior": "D",
            }

F = {"uníssono": "F",
            "2a menor": "Gb",
            "2a Maior": "G",
            "2a Aumentada": "G#",
            "3a menor": "Ab",
            "3a Maior": "A",
            "4a Justa": "Bb",
            "4a Aumentada": "B",
            "5a diminuta": "Cb",
            "5a Justa": "C",
            "5a Aumentada": "C#",
            "6a menor": "Db",
            "6a Maior": "D",
            "7a diminuta": "Ebb",
            "7a menor": "Eb",
            "7a Maior": "E",
            }

F_sus = {"uníssono": "F#",
         "2a menor": "G",
            "2a Maior": "G#",
            "2a Aumentada": "G##",
            "3a menor": "A",
            "3a Maior": "A#",
            "4a Justa": "B",
            "4a Aumentada": "B#",
            "5a diminuta": "C",
            "5a Justa": "C#",
            "5a Aumentada": "C##",
            "6a menor": "D",
            "6a Maior": "D#",
            "7a diminuta": "Eb",
            "7a menor": "E",
            "7a Maior": "E#",
            }

G = {"uníssono": "G",
            "2a menor": "Ab",
            "2a Maior": "A",
            "2a Aumentada": "A#",
            "3a menor": "Bb",
            "3a Maior": "B",
            "4a Justa": "C",
            "4a Aumentada": "C#",
            "5a diminuta": "Db",
            "5a Justa": "D",
            "5a Aumentada": "D#",
            "6a menor": "Eb",
            "6a Maior": "E",
            "7a diminuta": "Fb",
            "7a menor": "F",
            "7a Maior": "F#",
            }

G_sus = {"uníssono": "G#",
            "2a menor": "A",
            "2a Maior": "A#",
            "2a Aumentada": "A##",
            "3a menor": "B",
            "3a Maior": "B#",
            "4a Justa": "C#",
            "4a Aumentada": "C##",
            "5a diminuta": "D",
            "5a Justa": "D#",
            "5a Aumentada": "D##",
            "6a menor": "E",
            "6a Maior": "E#",
            "7a diminuta": "F",
            "7a menor": "F#",
            "7a Maior": "F##",
            }

G_b = {"uníssono": "Gb",
            "2a menor": "Abb",
            "2a Maior": "Ab",
            "2a Aumentada": "A",
            "3a menor": "Bbb",
            "3a Maior": "Bb",
            "4a Justa": "Cb",
            "4a Aumentada": "C",
            "5a diminuta": "Dbb",
            "5a Justa": "Db",
            "5a Aumentada": "D",
            "6a menor": "Ebb",
            "6a Maior": "Eb",
            "7a diminuta": "Fbb",
            "7a menor": "Fb",
            "7a Maior": "F",
            }

A = {"uníssono": "A",
            "2a menor": "Bb",
            "2a Maior": "B",
            "2a Aumentada": "B#",
            "3a menor": "C",
            "3a Maior": "C#",
            "4a Justa": "D",
            "4a Aumentada": "D#",
            "5a diminuta": "Eb",
            "5a Justa": "E",
            "5a Aumentada": "E#",
            "6a menor": "F",
            "6a Maior": "F#",
            "7a diminuta": "Gb",
            "7a menor": "G",
            "7a Maior": "G#",
            }

A_sus = {"uníssono": "A#",
            "2a menor": "B",
            "2a Maior": "B#",
            "2a Aumentada": "B##",
            "3a menor": "C#",
            "3a Maior": "C##",
            "4a Justa": "D#",
            "4a Aumentada": "D##",
            "5a diminuta": "E",
            "5a Justa": "E#",
            "5a Aumentada": "E##",
            "6a menor": "F#",
            "6a Maior": "F##",
            "7a diminuta": "G",
            "7a menor": "G#",
            "7a Maior": "G##",
            }

A_b = {"uníssono": "Ab",
            "2a menor": "Bbb",
            "2a Maior": "Bb",
            "2a Aumentada": "B",
            "3a menor": "Cb",
            "3a Maior": "C",
            "4a Justa": "Db",
            "4a Aumentada": "D",
            "5a diminuta": "Ebb",
            "5a Justa": "Eb",
            "5a Aumentada": "E",
            "6a menor": "Fb",
            "6a Maior": "F",
            "7a diminuta": "Gbb",
            "7a menor": "Gb",
            "7a Maior": "G",
            }

B = {"uníssono": "B",
            "2a menor": "C",
            "2a Maior": "C#",
            "2a Aumentada": "C##",
            "3a menor": "D",
            "3a Maior": "D#",
            "4a Justa": "E",
            "4a Aumentada": "E#",
            "5a diminuta": "F",
            "5a Justa": "F#",
            "5a Aumentada": "F##",
            "6a menor": "G",
            "6a Maior": "G#",
            "7a diminuta": "Ab",
            "7a menor": "A",
            "7a Maior": "A#",
            }

B_sus = {"uníssono": "B#",
            "2a menor": "C#",
            "2a Maior": "C##",
            "2a Aumentada": "C###",
            "3a menor": "D#",
            "3a Maior": "D##",
            "4a Justa": "E#",
            "4a Aumentada": "E##",
            "5a diminuta": "F#",
            "5a Justa": "F##",
            "5a Aumentada": "F###",
            "6a menor": "G#",
            "6a Maior": "G##",
            "7a diminuta": "A",
            "7a menor": "A#",
            "7a Maior": "A##",
            }

B_b = {"uníssono": "Bb",
            "2a menor": "Cb",
            "2a Maior": "C",
            "2a Aumentada": "C#",
            "3a menor": "Db",
            "3a Maior": "D",
            "4a Justa": "Eb",
            "4a Aumentada": "E",
            "5a diminuta": "Fb",
            "5a Justa": "F",
            "5a Aumentada": "F#",
            "6a menor": "Gb",
            "6a Maior": "G",
            "7a diminuta": "Abb",
            "7a menor": "Ab",
            "7a Maior": "A",
            }

fundamentais = [C, C_sus, C_b, D, D_sus, D_b, E, E_sus, E_b, F, F_sus, G, G_sus, G_b, A, A_sus, A_b, B, B_sus, B_b]
